language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -q fakeroot fakechroot cowdancer python-dateutil build-essential python-dev libgmp3-dev

install:
  - python bootstrap.py
  - ./bin/buildout

script: ./bin/test discover

