language: python
python:
  - "2.6"
  - "2.7"

cache:
    - /virtualenv/python2.6/lib/python2.6/site-packages/
    - /virtualenv/python2.6/lib/python2.7/site-packages/

install: pip install -r requirements.txt
script: coverage run $(which nose2)

after_success:
  - coveralls

notifications:
    irc: "irc.oftc.net#yaybu"
    on_success: change
    on_failure: always

